# Generated by Django 4.2.25 on 2025-10-07 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
                'db_table': 'priorities',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.priority')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-priority__weight', 'date_added'],
            },
        ),
    ]
